Update DSN-process_data.yml

diff --git a/.github/workflows/DSN-process_data.yml b/.github/workflows/DSN-process_data.yml
--- a/.github/workflows/DSN-process_data.yml
+++ b/.github/workflows/DSN-process_data.yml
@@ -41,16 +41,31 @@ jobs:
 
         echo "Run DSN_V02.py on each file:"
         for file in $FILES; do
-          echo "Processing $file"
-          python3 DSN_V02.py "DSNdata/NEW/$file"
+          new_file="DSNdata/NEW/$file"
+          arc_file="DSNdata/ARCHIVE/$file"
+          echo "Processing $new_file"
+          python3 DSN_V02.py $file"
+          if [ -f $arc_file ]; then
+            echo "$arc_file exists. Concatenating $new_file and $arc_file."
+            cat "$new_file" >> "$arc_file"
+          else
+            echo "$arc_file does not exist. Moving $new_file to $arc_file."
+            mv "$new_file" "$arc_file"
+          fi
+          if [ -f "$arc_file" ]; then
+            echo "$arc_file is in place."
+          else
+            echo "Error: $arc_file was not created."
+            exit 1
+          fi
         done
 
-    - name: Commit files # commit the INFLUX folder
+    - name: Commit files # commit the INFLUX and ARCHIVE folders
       run: |
         git config --local user.email "soazcomms@darksky.org"
         git config --local user.name "GitHub Action test"
         if [[ -n $(git status --porcelain) ]]; then
-          git add ./DSNdata/INFLUX
+          git add ./DSNdata/INFLUX ./DSNdata/ARCHIVE
           git commit -m "Add changes"
         else
           echo "No changes to commit"
