Update DSN-process_data.V02.yml

diff --git a/.github/workflows/DSN-process_data.V02.yml b/.github/workflows/DSN-process_data.V02.yml
--- a/.github/workflows/DSN-process_data.V02.yml
+++ b/.github/workflows/DSN-process_data.V02.yml
@@ -54,7 +54,7 @@ jobs:
             exit 1
           fi
           influx config rm default || true
-          influx bucket list
+          influx config ls
           echo "Run influx write on $IN_FILES"
           for infile in $IN_FILES; do
             echo "Uploading $infile to InfluxDB Cloud..."
@@ -66,11 +66,10 @@ jobs:
               --file "$infile" \
               --format csv \
               --debug
-
-          if [ $? -ne 0 ]; then
-            echo "Error: Failed to upload $infile to InfluxDB Cloud." >&2
-            exit 1
-          fi
+            if [ $? -ne 0 ]; then
+              echo "Error: Failed to upload $infile to InfluxDB Cloud." >&2
+              exit 1
+            fi
           done
           echo $CURRENT_DATE $ORIG_FILES" boxed." >> DSNdata/RUN_LOG
 
