Update DSN-updates.yml

diff --git a/.github/workflows/DSN-updates.yml b/.github/workflows/DSN-updates.yml
--- a/.github/workflows/DSN-updates.yml
+++ b/.github/workflows/DSN-updates.yml
@@ -11,17 +11,27 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: Install Influx CLI
+      - name: Install Influx CLI Manually
         run: |
           echo "Downloading and installing Influx CLI..."
           curl -sL https://dl.influxdata.com/influxdb/releases/influxdb2-client-2.7.5-linux-amd64.tar.gz -o influxdb2-client.tar.gz
-          tar xvzf influxdb2-client.tar.gz 
-          echo "Finding the extracted directory..."
-          EXTRACTED_DIR=$(find . -type d -name 'influxdb2-client-*')
-          echo "where we are:"
-          pwd
-          echo "Extracted directory: $EXTRACTED_DIR"
-          sudo mv "$EXTRACTED_DIR/influx" /usr/local/bin/
+          tar xvzf influxdb2-client.tar.gz
+          echo "Listing contents of current directory after extraction:"
+          ls -l
+          echo "Checking if 'influx' binary exists directly after extraction:"
+          if [ -f influx ]; then
+            sudo mv influx /usr/local/bin/
+          else
+            echo "'influx' binary not found directly. Checking for extracted directory..."
+            EXTRACTED_DIR=$(find . -type d -name 'influxdb2-client-*')
+            if [ -d "$EXTRACTED_DIR" ]; then
+              echo "Found extracted directory: $EXTRACTED_DIR"
+              sudo mv "$EXTRACTED_DIR/influx" /usr/local/bin/
+            else
+              echo "No valid directory or binary found. Exiting with error."
+              exit 1
+            fi
+          fi
           echo "Influx CLI installed to /usr/local/bin"
           which influx
           influx version
